[package]
name = "rsb-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = "s"
strip = true

[dependencies]
gumdrop = "0.8"
thiserror = "1.0"

[build-dependencies]
quote = "1.0"